### ISSUE TITLE
Reporting instances

### ISSUE THREAD

**Issue by JOHNRUNE** [NIVANorge/orderform-NIVAlab-data-management#2]
A project may have several reporting instances, but you are only allowed to select one from the list. Users may type in an extra in the cell, but users are not that intuitive. Maybe we should change leading text to: "If selected instance does not meet your need, please feel free to type any text in the cell"

**Comment by jeved** [comment]
We need a norwegian text.

In the last version, the text is : "_Velg fra listen, eller skriv inn hvis rapporteringsinstans ikke vises i listen_"
Change to:  "_Velg fra listen, eller skriv inn hvis aktuell rapporteringsinstans, eller kombinasjon av rapporteringsinstanser ikke vises i listen_"???

We can also add "_Vannmiljø + ICES_" to the list of possible predefined choices. OK/other suggestions?
