### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by JOHNRUNE** [NIVANorge/orderform-NIVAlab-data-management#3]
User perceive to only tick off those data types that are not flowing via NIVAlab. Leading text may be changed to: "Angi hvor data finnes" ("describe where data is located").

**Comment by jeved** [comment]
I have fixed the text in the field.

I will not update the file in TQM for now, only push to this repository. It is a lot of work to update in TQM, so I suggest we wait for more changes before uploading a new version

**Comment by jeved** [comment]
Solved in 576fca37c57ddea598cb8397db693e3c40568d4f
