### ISSUE TITLE
Forslag til innhold i "Gul boks"

### ISSUE THREAD

**Issue by roarbra** [NIVANorge/orderform-NIVAlab-data-management#9]
- Linken som ligger i boksen peker på feil side i Kilden. Her er riktig url: https://niva365.sharepoint.com/sites/kilden/sitepages/Bestilling-laboratorieanalyser-og-datah%C3%A5ndtering.aspx

- Jeg ønsker en omrokkering av teksten i boksen. Det står litt hulter til bulter med Tips og NB.

- Og jeg ønsker at det eksplisitt skal stå at skjema skal lagres i Nivadok. Kanskje også med en melding om å sende e-post, men skulle det ikke være mulig å fange opp dette i Nivadok?

Forslag til utforming:
```
De to øverste feltene er felles for laboratorieanalyser og dataforvaltning. Linje tre er for laboratorieanalyser, mens resten gjelder dataforvaltning.
Ytterligere forklaring av feltene kan du få ved å markere feltet i kolonne B.

Ferdig utfylt skjema lagres i NIVAdok under [Bestillinger dataforvaltning](http://nivadok/otcs/llisapi.dll?func=ll&objId=2588397&objAction=browse&viewType=1).

Instrukser for utfylling finnes også på Kilden. Trykk på denne tekstboksen for å komme rett til siden.
```

**Comment by jeved** [comment]
Is this fixed? I couldn't find any commits?

**Comment by jeved** [comment]
I think we should discuss if we want it to be compulsory to store in nivadok.  My experience is that it works much better with order forms in the researcers own project spaces on K...

I think we should wait to see what is happening with the web ordering Viviane is preparing before we do any changes to the orderform.
